### ISSUE TITLE
Systems are empty

### ISSUE THREAD

**Issue by OracleToes** [golightlyb/tao#12]
Only mod enabled is this one, the starting system is populated, but all other systems i warp to are completely empty.

**Comment by golightlyb** [comment]
Thank you very much for the bug report.

Could you upload the log file in the galaxy save directory?

**Comment by OracleToes** [comment]
[serverlog 2023-08-30 20-55-00.txt](https://github.com/golightlyb/tao/files/12481825/serverlog.2023-08-30.20-55-00.txt)
Here's the server log file, will that do?

**Comment by golightlyb** [comment]
Thanks so much!

It's super odd and looks like some files are missing, not even modded files.

Could you verify the game files (https://help.steampowered.com/en/faqs/view/0C48-FCBD-DA71-93EB) and see if that helps?

**Comment by OracleToes** [comment]
I verified the files, and then made a new galaxy, and it's the same
[serverlog 2023-08-31 05-09-25.txt](https://github.com/golightlyb/tao/files/12485525/serverlog.2023-08-31.05-09-25.txt)
I'm running linux and using the linux version, would that make a difference?

**Comment by golightlyb** [comment]
Ah, yes it would. Linux has a case sensitive file system and avorion has a couple of files where its inconsistent if they use uppercase or lowercase.

Fortunately I think that's something I can easily fix thanks to your log files. I'll try have this sorted this weekend.

Thank you for the super helpful info!

**Comment by OracleToes** [comment]
You're welcome, thanks for helping with this. I really want to try out your mod!

**Comment by neutrino1911** [comment]
Hey @OracleToes, in the meantime I believe you could try to manually fix this by creating a symlink.
`cd ~/.local/share/Steam/steamapps/workshop/content/445220/3007442662/data/scripts; ln -s sectorspecifics.lua SectorSpecifics.lua; cd`

**Comment by golightlyb** [comment]
Good news! The new version on the workshop should fix this, but please let me know if it doesn't.
