### ISSUE TITLE
Mod breaks Tutorial

### ISSUE THREAD

**Issue by Kraegor1977** [golightlyb/tao#4]
If you start the game with Tutorial enabled when you get to the part where you click on Missions for your new quest, it is blank and it says "No Mission Available".  This locks the screen and keeps the tutorial text up because you cannot click anywhere else.  Also disables the ESC key so you can't exit the game.  You can only force quit out of the game, which upon entering the game.. re-enables the tutorial, in which the whole cycle repeats itself.

This does not happen if you start a game with no tutorial enabled.

**Comment by golightlyb** [comment]
Thanks very much for the bug report!

**Comment by golightlyb** [comment]
🎉 now fixed on the workshop version
