### ISSUE TITLE
Xsotan event

### ISSUE THREAD

**Issue by Lorrdy** [golightlyb/tao#7]
I somehow got the Xsotan attack event on a ai (outside) sector after a few "signal get stronger" messages. 
I thought they don't exists.

**Comment by golightlyb** [comment]
Hmmm that's interesting, thanks for the report!

**Comment by golightlyb** [comment]
I definitely just had a vanilla pirate raid on the starting sector too, so evidently some events are sneaking in somewhere.

**Comment by golightlyb** [comment]
Okay this should hopefully be fixed now!
