### ISSUE TITLE
Turret needs more than one slot

### ISSUE THREAD

**Issue by Lorrdy** [golightlyb/tao#8]
From that here 
"vastly reduced turret slots, but...
weapons don't take up more slots as they get bigger
so you have fewer weapons
but as you progress those weapons can get bigger and better"
I got the feeling turrets size isn't relevant for the slots they take. But as you can see a bigger turret still take up more slots. 
Not sure whether it was intentional and I just misunderstood.
![image](https://github.com/golightlyb/tao/assets/34692368/6625596f-2aaa-444a-aa73-77fdf66fe9a5)

**Comment by golightlyb** [comment]
Yes - it depends on type.

Artillery Cannons - 4 slots
Micromissile - 2 slots
Disruptor - 2 slots
Autocannon - 1 slot

But no matter how big those types are, they take up the same number of slots.

 I should make this clearer in the readme. Thank you!
